[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1F2937"
backgroundColor = "#F5F5F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[client]
toolbarMode = "minimal"
